spring:
  datasource:
    url: jdbc:mysql://uclee-mysql.mysql.database.azure.com:3306/security_and_privacy?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Europe/London&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ie_mysql
    password: virmer-7fywse-wiRzut
  jpa:
    hibernate:
    ddl-auto: update
    show-sql: true